// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDRgLf8-plzZqe_JU8Wi-c6Vbtv1daYjQ',
    appId: '1:964385688841:web:0ffb11010e1f680c84d7d8',
    messagingSenderId: '964385688841',
    projectId: 'flutter-firebase-app-35f75',
    authDomain: 'flutter-firebase-app-35f75.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-35f75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc8r_YACQNXvRBsSkHx_w-bIIrIKCyiCY',
    appId: '1:964385688841:android:747c77b7f14d5c8e84d7d8',
    messagingSenderId: '964385688841',
    projectId: 'flutter-firebase-app-35f75',
    storageBucket: 'flutter-firebase-app-35f75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRTFKd3ASvkP6TuMNguJfJdnPKIRSZdEo',
    appId: '1:964385688841:ios:fed575130301072184d7d8',
    messagingSenderId: '964385688841',
    projectId: 'flutter-firebase-app-35f75',
    storageBucket: 'flutter-firebase-app-35f75.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRTFKd3ASvkP6TuMNguJfJdnPKIRSZdEo',
    appId: '1:964385688841:ios:fed575130301072184d7d8',
    messagingSenderId: '964385688841',
    projectId: 'flutter-firebase-app-35f75',
    storageBucket: 'flutter-firebase-app-35f75.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDRgLf8-plzZqe_JU8Wi-c6Vbtv1daYjQ',
    appId: '1:964385688841:web:39bfa5eab2e3b63a84d7d8',
    messagingSenderId: '964385688841',
    projectId: 'flutter-firebase-app-35f75',
    authDomain: 'flutter-firebase-app-35f75.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-35f75.firebasestorage.app',
  );
}
